var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                    h           ",
   "                                                                    x           ",
   "                                             yyyyy                 xxx          ",
   "    yyyyy                                           x             xxxxx         ",
   "                              yyyyy             x                               ",
   "                                       xx   x          yyyyy     x!!!!!x        ",
   "               yyyyy            l                               xxx!!!xxx       ",
   "                             xxxxxxx                           xxxxx!xxxxx      ",
   "                                                       x   x        !           ",
   "   @               yyyyy               xxxxx                        !       xx  ",
   "  xx                                                                !        x  ",
   "   x                    o    xxxxxxx               yyyyy            !        x  ",
   "   x           o      xxxxx                                         !o       x  ",
   "   x!!!!!xxxxxxxxx                                              !!!!!!!      x  ",
   "   x!!!!!x       x                                           !!!!xxxxx!!!!!!!x  ",
   "   xxxxxxx       xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxx   xxxxxxxxx  ",
   "                  xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                 ",
   "                   xx!!!!!!!!!!!!!!!!!xxxx!!!!!!!!!!!!!!!!!!xxx                 ",
   "                    xxx!!!!!!!!!!!!!xxx  xx!!!!!!!!!!!!!!!!!x                   ",
   "                      xxxxxx!!xxxxxxx     xxx!!xxx!!!xxxxxxxx                   ",
   "                           xxxx             xxxx xxxxx                          ",
   "                                                                                "],
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                   x o xxxx                                                     ",
   "                   x   x                                                        ",
   "                   x   x                                                        ",
   "         x         x   x                                                        ",
   "         |         x  lx                                                        ",
   "                   x   x                                                        ",
   "                   x   x                                                        ",
   "                       x                                                        ",
   "                       x                                                        ",
   "       x   x   xxxxxxxxx                                                        ",
   "   o                                                                            ",
   "   x                                                                            ",
   "   xx                                                                           ",
   "    xxx                                o      o                                 ",
   "    xxxx          @                 x!!!!!!!!!!!!x      o       x               ",
   "    xxxxx    xxxxxxxxxxx             x!!!!!!!!!!x    xxxxxxx    x               ",
   "    xxx      x         x             x!!!!!!!!!!x               x               ",
   "    xxx  |   x         x              x!!!!!!!!x                x               ",
   "!!!!xxx!!!!!!x         x!!!!!!x       xxxx||xxxx      h         x               ",
   "!!!!xxx!!!!!!x         x!!!!!xx                                 x               ",
   "!!!!xxx!!!!!!x         x!!!!!x    o                             x               ",
   "!!!!xxx!!!!!!x         x!!!!!x                     xx!!!!!!!!!!!!               ",
   "!!!!xxx!!!!!!x         x!!!!!xx       xxxxxxxxxxxxxx!!!!!!!!!!!!!!!             ",
   "!!!!xxx!!!!!!x         x!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!           ",
   "!!!!xxx!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!         "],
  ["                                                              ",
   "                                                              ",
   "                                                              ",
   "                                                              ",
   "                                                              ",
   "                                                              ",
   "                                                  o           ",
   "                                                  x           ",
   "                                                  x           ",
   "                                                x x x         ",
   "                                                 xxx          ",
   "                                                  x           ",
   "                                                              ",
   "                            o       x    xxxxxx               ",
   "                          xxxxx     x                         ",
   "                         xx!!!xx    x                         ",
   "                          xx!xx     x                         ",
   "                            v       x                         ",
   "                                    x                         ",
   "             x                      x                         ",
   "             x                                                ",
   "             x       x                 x                      ",
   "             x       x                 x                      ",
   "             x   =   x                 x                      ",
   "             x       x                 x                      ",
   "             x       x                 x                      ",
   "             x       x      x          x                      ",
   "             x       x            o    x                      ",
   "        o            x           xxx                          ",
   " x    xxxxx         lx                                        ",
   " x                                                            ",
   " x                                                            ",
   " x                                                            ",
   " x                                                            ",
   " x                                                            ",
   "                                                              ",
   "      x                                                       ",
   "      x                                                       ",
   "      x                                                       ",
   "      x                                                       ",
   "      x                                                       ",
   "      x                                            h          ",
   "  @                                             xxxxxxx       ",
   "xxxxx    o                                                    ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["                                       ",
   "                                       ",
   "       !   ! !!! !  ! !  ! !!!! !!     ",
   "       !   !  !  !! ! !! ! !    ! !    ",
   "       ! ! !  !  ! !! ! !! !!!  !  !   ",
   "        ! !  !!! !  ! !  ! !    ! !    ",
   "                           !!!! !!     ",
   "                                ! !    ",
   "                          @     !  !   ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
